/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TodoItem } from "./components/models";
export namespace Components {
    interface AppRoot {
    }
    interface ListItem {
    }
    interface TodoCreator {
    }
    interface TodoItems {
        "item": TodoItem;
    }
    interface TodoList {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLListItemElement extends Components.ListItem, HTMLStencilElement {
    }
    var HTMLListItemElement: {
        prototype: HTMLListItemElement;
        new (): HTMLListItemElement;
    };
    interface HTMLTodoCreatorElement extends Components.TodoCreator, HTMLStencilElement {
    }
    var HTMLTodoCreatorElement: {
        prototype: HTMLTodoCreatorElement;
        new (): HTMLTodoCreatorElement;
    };
    interface HTMLTodoItemsElement extends Components.TodoItems, HTMLStencilElement {
    }
    var HTMLTodoItemsElement: {
        prototype: HTMLTodoItemsElement;
        new (): HTMLTodoItemsElement;
    };
    interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {
    }
    var HTMLTodoListElement: {
        prototype: HTMLTodoListElement;
        new (): HTMLTodoListElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "list-item": HTMLListItemElement;
        "todo-creator": HTMLTodoCreatorElement;
        "todo-items": HTMLTodoItemsElement;
        "todo-list": HTMLTodoListElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface ListItem {
    }
    interface TodoCreator {
    }
    interface TodoItems {
        "item"?: TodoItem;
    }
    interface TodoList {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "list-item": ListItem;
        "todo-creator": TodoCreator;
        "todo-items": TodoItems;
        "todo-list": TodoList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "list-item": LocalJSX.ListItem & JSXBase.HTMLAttributes<HTMLListItemElement>;
            "todo-creator": LocalJSX.TodoCreator & JSXBase.HTMLAttributes<HTMLTodoCreatorElement>;
            "todo-items": LocalJSX.TodoItems & JSXBase.HTMLAttributes<HTMLTodoItemsElement>;
            "todo-list": LocalJSX.TodoList & JSXBase.HTMLAttributes<HTMLTodoListElement>;
        }
    }
}
