/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppArticle {
        "json": any;
        "onlikeClick": any;
    }
    interface AppArticles {
        "id_articles": number;
        "id_tema": number;
        "obnowFuctions": any;
    }
    interface AppComent {
        "id_articles": any;
        "obnowFuctions": any;
        "user": any;
    }
    interface AppComents {
        "idComent": number;
        "obnowFuctions": any;
        "sendMessages": any;
    }
    interface AppGame {
    }
    interface AppHeader {
    }
    interface AppHome {
        "id_articles": number;
        "id_tema": number;
    }
    interface AppMenu {
        "name_menu": string;
    }
    interface AppRegistration {
        "jsons": any;
    }
    interface AppRoot {
    }
    interface AppSitebar {
    }
    interface AppUser {
        "jsons": any;
    }
    interface DarkMode {
    }
    interface MyFab {
    }
}
declare global {
    interface HTMLAppArticleElement extends Components.AppArticle, HTMLStencilElement {
    }
    var HTMLAppArticleElement: {
        prototype: HTMLAppArticleElement;
        new (): HTMLAppArticleElement;
    };
    interface HTMLAppArticlesElement extends Components.AppArticles, HTMLStencilElement {
    }
    var HTMLAppArticlesElement: {
        prototype: HTMLAppArticlesElement;
        new (): HTMLAppArticlesElement;
    };
    interface HTMLAppComentElement extends Components.AppComent, HTMLStencilElement {
    }
    var HTMLAppComentElement: {
        prototype: HTMLAppComentElement;
        new (): HTMLAppComentElement;
    };
    interface HTMLAppComentsElement extends Components.AppComents, HTMLStencilElement {
    }
    var HTMLAppComentsElement: {
        prototype: HTMLAppComentsElement;
        new (): HTMLAppComentsElement;
    };
    interface HTMLAppGameElement extends Components.AppGame, HTMLStencilElement {
    }
    var HTMLAppGameElement: {
        prototype: HTMLAppGameElement;
        new (): HTMLAppGameElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppMenuElement extends Components.AppMenu, HTMLStencilElement {
    }
    var HTMLAppMenuElement: {
        prototype: HTMLAppMenuElement;
        new (): HTMLAppMenuElement;
    };
    interface HTMLAppRegistrationElement extends Components.AppRegistration, HTMLStencilElement {
    }
    var HTMLAppRegistrationElement: {
        prototype: HTMLAppRegistrationElement;
        new (): HTMLAppRegistrationElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSitebarElement extends Components.AppSitebar, HTMLStencilElement {
    }
    var HTMLAppSitebarElement: {
        prototype: HTMLAppSitebarElement;
        new (): HTMLAppSitebarElement;
    };
    interface HTMLAppUserElement extends Components.AppUser, HTMLStencilElement {
    }
    var HTMLAppUserElement: {
        prototype: HTMLAppUserElement;
        new (): HTMLAppUserElement;
    };
    interface HTMLDarkModeElement extends Components.DarkMode, HTMLStencilElement {
    }
    var HTMLDarkModeElement: {
        prototype: HTMLDarkModeElement;
        new (): HTMLDarkModeElement;
    };
    interface HTMLMyFabElement extends Components.MyFab, HTMLStencilElement {
    }
    var HTMLMyFabElement: {
        prototype: HTMLMyFabElement;
        new (): HTMLMyFabElement;
    };
    interface HTMLElementTagNameMap {
        "app-article": HTMLAppArticleElement;
        "app-articles": HTMLAppArticlesElement;
        "app-coment": HTMLAppComentElement;
        "app-coments": HTMLAppComentsElement;
        "app-game": HTMLAppGameElement;
        "app-header": HTMLAppHeaderElement;
        "app-home": HTMLAppHomeElement;
        "app-menu": HTMLAppMenuElement;
        "app-registration": HTMLAppRegistrationElement;
        "app-root": HTMLAppRootElement;
        "app-sitebar": HTMLAppSitebarElement;
        "app-user": HTMLAppUserElement;
        "dark-mode": HTMLDarkModeElement;
        "my-fab": HTMLMyFabElement;
    }
}
declare namespace LocalJSX {
    interface AppArticle {
        "json"?: any;
        "onlikeClick"?: any;
    }
    interface AppArticles {
        "id_articles"?: number;
        "id_tema"?: number;
        "obnowFuctions"?: any;
    }
    interface AppComent {
        "id_articles"?: any;
        "obnowFuctions"?: any;
        "user"?: any;
    }
    interface AppComents {
        "idComent"?: number;
        "obnowFuctions"?: any;
        "sendMessages"?: any;
    }
    interface AppGame {
    }
    interface AppHeader {
    }
    interface AppHome {
        "id_articles"?: number;
        "id_tema"?: number;
    }
    interface AppMenu {
        "name_menu"?: string;
    }
    interface AppRegistration {
        "jsons"?: any;
    }
    interface AppRoot {
    }
    interface AppSitebar {
    }
    interface AppUser {
        "jsons"?: any;
    }
    interface DarkMode {
    }
    interface MyFab {
    }
    interface IntrinsicElements {
        "app-article": AppArticle;
        "app-articles": AppArticles;
        "app-coment": AppComent;
        "app-coments": AppComents;
        "app-game": AppGame;
        "app-header": AppHeader;
        "app-home": AppHome;
        "app-menu": AppMenu;
        "app-registration": AppRegistration;
        "app-root": AppRoot;
        "app-sitebar": AppSitebar;
        "app-user": AppUser;
        "dark-mode": DarkMode;
        "my-fab": MyFab;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-article": LocalJSX.AppArticle & JSXBase.HTMLAttributes<HTMLAppArticleElement>;
            "app-articles": LocalJSX.AppArticles & JSXBase.HTMLAttributes<HTMLAppArticlesElement>;
            "app-coment": LocalJSX.AppComent & JSXBase.HTMLAttributes<HTMLAppComentElement>;
            "app-coments": LocalJSX.AppComents & JSXBase.HTMLAttributes<HTMLAppComentsElement>;
            "app-game": LocalJSX.AppGame & JSXBase.HTMLAttributes<HTMLAppGameElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-menu": LocalJSX.AppMenu & JSXBase.HTMLAttributes<HTMLAppMenuElement>;
            "app-registration": LocalJSX.AppRegistration & JSXBase.HTMLAttributes<HTMLAppRegistrationElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-sitebar": LocalJSX.AppSitebar & JSXBase.HTMLAttributes<HTMLAppSitebarElement>;
            "app-user": LocalJSX.AppUser & JSXBase.HTMLAttributes<HTMLAppUserElement>;
            "dark-mode": LocalJSX.DarkMode & JSXBase.HTMLAttributes<HTMLDarkModeElement>;
            "my-fab": LocalJSX.MyFab & JSXBase.HTMLAttributes<HTMLMyFabElement>;
        }
    }
}
