/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppArticles {
    }
    interface AppGame {
    }
    interface AppHeader {
    }
    interface AppHome {
    }
    interface AppMenu {
        "name_menu": string;
    }
    interface AppRoot {
    }
    interface AppSitebar {
    }
    interface AppUser {
    }
    interface DarkMode {
    }
    interface MyFab {
    }
}
declare global {
    interface HTMLAppArticlesElement extends Components.AppArticles, HTMLStencilElement {
    }
    var HTMLAppArticlesElement: {
        prototype: HTMLAppArticlesElement;
        new (): HTMLAppArticlesElement;
    };
    interface HTMLAppGameElement extends Components.AppGame, HTMLStencilElement {
    }
    var HTMLAppGameElement: {
        prototype: HTMLAppGameElement;
        new (): HTMLAppGameElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppMenuElement extends Components.AppMenu, HTMLStencilElement {
    }
    var HTMLAppMenuElement: {
        prototype: HTMLAppMenuElement;
        new (): HTMLAppMenuElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSitebarElement extends Components.AppSitebar, HTMLStencilElement {
    }
    var HTMLAppSitebarElement: {
        prototype: HTMLAppSitebarElement;
        new (): HTMLAppSitebarElement;
    };
    interface HTMLAppUserElement extends Components.AppUser, HTMLStencilElement {
    }
    var HTMLAppUserElement: {
        prototype: HTMLAppUserElement;
        new (): HTMLAppUserElement;
    };
    interface HTMLDarkModeElement extends Components.DarkMode, HTMLStencilElement {
    }
    var HTMLDarkModeElement: {
        prototype: HTMLDarkModeElement;
        new (): HTMLDarkModeElement;
    };
    interface HTMLMyFabElement extends Components.MyFab, HTMLStencilElement {
    }
    var HTMLMyFabElement: {
        prototype: HTMLMyFabElement;
        new (): HTMLMyFabElement;
    };
    interface HTMLElementTagNameMap {
        "app-articles": HTMLAppArticlesElement;
        "app-game": HTMLAppGameElement;
        "app-header": HTMLAppHeaderElement;
        "app-home": HTMLAppHomeElement;
        "app-menu": HTMLAppMenuElement;
        "app-root": HTMLAppRootElement;
        "app-sitebar": HTMLAppSitebarElement;
        "app-user": HTMLAppUserElement;
        "dark-mode": HTMLDarkModeElement;
        "my-fab": HTMLMyFabElement;
    }
}
declare namespace LocalJSX {
    interface AppArticles {
    }
    interface AppGame {
    }
    interface AppHeader {
    }
    interface AppHome {
    }
    interface AppMenu {
        "name_menu"?: string;
    }
    interface AppRoot {
    }
    interface AppSitebar {
    }
    interface AppUser {
    }
    interface DarkMode {
    }
    interface MyFab {
    }
    interface IntrinsicElements {
        "app-articles": AppArticles;
        "app-game": AppGame;
        "app-header": AppHeader;
        "app-home": AppHome;
        "app-menu": AppMenu;
        "app-root": AppRoot;
        "app-sitebar": AppSitebar;
        "app-user": AppUser;
        "dark-mode": DarkMode;
        "my-fab": MyFab;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-articles": LocalJSX.AppArticles & JSXBase.HTMLAttributes<HTMLAppArticlesElement>;
            "app-game": LocalJSX.AppGame & JSXBase.HTMLAttributes<HTMLAppGameElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-menu": LocalJSX.AppMenu & JSXBase.HTMLAttributes<HTMLAppMenuElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-sitebar": LocalJSX.AppSitebar & JSXBase.HTMLAttributes<HTMLAppSitebarElement>;
            "app-user": LocalJSX.AppUser & JSXBase.HTMLAttributes<HTMLAppUserElement>;
            "dark-mode": LocalJSX.DarkMode & JSXBase.HTMLAttributes<HTMLDarkModeElement>;
            "my-fab": LocalJSX.MyFab & JSXBase.HTMLAttributes<HTMLMyFabElement>;
        }
    }
}
