/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppAdmin {
    }
    interface AppAdminFilter {
        "items": any;
    }
    interface AppAdminHeader {
    }
    interface AppAdminId {
        "idItem": string;
    }
    interface AppAdminIdArticle {
        "article": any;
    }
    interface AppAdminItem {
        "article": any;
    }
    interface AppAdminItems {
        "db": any;
    }
    interface AppAdminMenu {
    }
    interface AppAdminSearch {
    }
    interface AppAdminSort {
    }
    interface AppArticleId {
        "idItem": string;
    }
    interface AppArticles {
    }
    interface AppArticlesFilter {
        "items": any;
    }
    interface AppArticlesHeader {
    }
    interface AppArticlesItem {
        "article": any;
    }
    interface AppArticlesItems {
        "db": any;
    }
    interface AppArticlesMenu {
    }
    interface AppArticlesPrice {
        "initialMax": any;
        "initialMin": any;
    }
    interface AppArticlesSearch {
    }
    interface AppArticlesSort {
    }
    interface AppCreateItem {
    }
    interface AppFormId {
        "item": any;
    }
    interface AppHeaderItem {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppAdminElement extends Components.AppAdmin, HTMLStencilElement {
    }
    var HTMLAppAdminElement: {
        prototype: HTMLAppAdminElement;
        new (): HTMLAppAdminElement;
    };
    interface HTMLAppAdminFilterElement extends Components.AppAdminFilter, HTMLStencilElement {
    }
    var HTMLAppAdminFilterElement: {
        prototype: HTMLAppAdminFilterElement;
        new (): HTMLAppAdminFilterElement;
    };
    interface HTMLAppAdminHeaderElement extends Components.AppAdminHeader, HTMLStencilElement {
    }
    var HTMLAppAdminHeaderElement: {
        prototype: HTMLAppAdminHeaderElement;
        new (): HTMLAppAdminHeaderElement;
    };
    interface HTMLAppAdminIdElement extends Components.AppAdminId, HTMLStencilElement {
    }
    var HTMLAppAdminIdElement: {
        prototype: HTMLAppAdminIdElement;
        new (): HTMLAppAdminIdElement;
    };
    interface HTMLAppAdminIdArticleElement extends Components.AppAdminIdArticle, HTMLStencilElement {
    }
    var HTMLAppAdminIdArticleElement: {
        prototype: HTMLAppAdminIdArticleElement;
        new (): HTMLAppAdminIdArticleElement;
    };
    interface HTMLAppAdminItemElement extends Components.AppAdminItem, HTMLStencilElement {
    }
    var HTMLAppAdminItemElement: {
        prototype: HTMLAppAdminItemElement;
        new (): HTMLAppAdminItemElement;
    };
    interface HTMLAppAdminItemsElement extends Components.AppAdminItems, HTMLStencilElement {
    }
    var HTMLAppAdminItemsElement: {
        prototype: HTMLAppAdminItemsElement;
        new (): HTMLAppAdminItemsElement;
    };
    interface HTMLAppAdminMenuElement extends Components.AppAdminMenu, HTMLStencilElement {
    }
    var HTMLAppAdminMenuElement: {
        prototype: HTMLAppAdminMenuElement;
        new (): HTMLAppAdminMenuElement;
    };
    interface HTMLAppAdminSearchElement extends Components.AppAdminSearch, HTMLStencilElement {
    }
    var HTMLAppAdminSearchElement: {
        prototype: HTMLAppAdminSearchElement;
        new (): HTMLAppAdminSearchElement;
    };
    interface HTMLAppAdminSortElement extends Components.AppAdminSort, HTMLStencilElement {
    }
    var HTMLAppAdminSortElement: {
        prototype: HTMLAppAdminSortElement;
        new (): HTMLAppAdminSortElement;
    };
    interface HTMLAppArticleIdElement extends Components.AppArticleId, HTMLStencilElement {
    }
    var HTMLAppArticleIdElement: {
        prototype: HTMLAppArticleIdElement;
        new (): HTMLAppArticleIdElement;
    };
    interface HTMLAppArticlesElement extends Components.AppArticles, HTMLStencilElement {
    }
    var HTMLAppArticlesElement: {
        prototype: HTMLAppArticlesElement;
        new (): HTMLAppArticlesElement;
    };
    interface HTMLAppArticlesFilterElement extends Components.AppArticlesFilter, HTMLStencilElement {
    }
    var HTMLAppArticlesFilterElement: {
        prototype: HTMLAppArticlesFilterElement;
        new (): HTMLAppArticlesFilterElement;
    };
    interface HTMLAppArticlesHeaderElement extends Components.AppArticlesHeader, HTMLStencilElement {
    }
    var HTMLAppArticlesHeaderElement: {
        prototype: HTMLAppArticlesHeaderElement;
        new (): HTMLAppArticlesHeaderElement;
    };
    interface HTMLAppArticlesItemElement extends Components.AppArticlesItem, HTMLStencilElement {
    }
    var HTMLAppArticlesItemElement: {
        prototype: HTMLAppArticlesItemElement;
        new (): HTMLAppArticlesItemElement;
    };
    interface HTMLAppArticlesItemsElement extends Components.AppArticlesItems, HTMLStencilElement {
    }
    var HTMLAppArticlesItemsElement: {
        prototype: HTMLAppArticlesItemsElement;
        new (): HTMLAppArticlesItemsElement;
    };
    interface HTMLAppArticlesMenuElement extends Components.AppArticlesMenu, HTMLStencilElement {
    }
    var HTMLAppArticlesMenuElement: {
        prototype: HTMLAppArticlesMenuElement;
        new (): HTMLAppArticlesMenuElement;
    };
    interface HTMLAppArticlesPriceElement extends Components.AppArticlesPrice, HTMLStencilElement {
    }
    var HTMLAppArticlesPriceElement: {
        prototype: HTMLAppArticlesPriceElement;
        new (): HTMLAppArticlesPriceElement;
    };
    interface HTMLAppArticlesSearchElement extends Components.AppArticlesSearch, HTMLStencilElement {
    }
    var HTMLAppArticlesSearchElement: {
        prototype: HTMLAppArticlesSearchElement;
        new (): HTMLAppArticlesSearchElement;
    };
    interface HTMLAppArticlesSortElement extends Components.AppArticlesSort, HTMLStencilElement {
    }
    var HTMLAppArticlesSortElement: {
        prototype: HTMLAppArticlesSortElement;
        new (): HTMLAppArticlesSortElement;
    };
    interface HTMLAppCreateItemElement extends Components.AppCreateItem, HTMLStencilElement {
    }
    var HTMLAppCreateItemElement: {
        prototype: HTMLAppCreateItemElement;
        new (): HTMLAppCreateItemElement;
    };
    interface HTMLAppFormIdElement extends Components.AppFormId, HTMLStencilElement {
    }
    var HTMLAppFormIdElement: {
        prototype: HTMLAppFormIdElement;
        new (): HTMLAppFormIdElement;
    };
    interface HTMLAppHeaderItemElement extends Components.AppHeaderItem, HTMLStencilElement {
    }
    var HTMLAppHeaderItemElement: {
        prototype: HTMLAppHeaderItemElement;
        new (): HTMLAppHeaderItemElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-admin": HTMLAppAdminElement;
        "app-admin-filter": HTMLAppAdminFilterElement;
        "app-admin-header": HTMLAppAdminHeaderElement;
        "app-admin-id": HTMLAppAdminIdElement;
        "app-admin-id-article": HTMLAppAdminIdArticleElement;
        "app-admin-item": HTMLAppAdminItemElement;
        "app-admin-items": HTMLAppAdminItemsElement;
        "app-admin-menu": HTMLAppAdminMenuElement;
        "app-admin-search": HTMLAppAdminSearchElement;
        "app-admin-sort": HTMLAppAdminSortElement;
        "app-article-id": HTMLAppArticleIdElement;
        "app-articles": HTMLAppArticlesElement;
        "app-articles-filter": HTMLAppArticlesFilterElement;
        "app-articles-header": HTMLAppArticlesHeaderElement;
        "app-articles-item": HTMLAppArticlesItemElement;
        "app-articles-items": HTMLAppArticlesItemsElement;
        "app-articles-menu": HTMLAppArticlesMenuElement;
        "app-articles-price": HTMLAppArticlesPriceElement;
        "app-articles-search": HTMLAppArticlesSearchElement;
        "app-articles-sort": HTMLAppArticlesSortElement;
        "app-create-item": HTMLAppCreateItemElement;
        "app-form-id": HTMLAppFormIdElement;
        "app-header-item": HTMLAppHeaderItemElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppAdmin {
    }
    interface AppAdminFilter {
        "items"?: any;
    }
    interface AppAdminHeader {
    }
    interface AppAdminId {
        "idItem"?: string;
    }
    interface AppAdminIdArticle {
        "article"?: any;
    }
    interface AppAdminItem {
        "article"?: any;
    }
    interface AppAdminItems {
        "db"?: any;
    }
    interface AppAdminMenu {
    }
    interface AppAdminSearch {
    }
    interface AppAdminSort {
    }
    interface AppArticleId {
        "idItem"?: string;
    }
    interface AppArticles {
    }
    interface AppArticlesFilter {
        "items"?: any;
    }
    interface AppArticlesHeader {
    }
    interface AppArticlesItem {
        "article"?: any;
    }
    interface AppArticlesItems {
        "db"?: any;
    }
    interface AppArticlesMenu {
    }
    interface AppArticlesPrice {
        "initialMax"?: any;
        "initialMin"?: any;
    }
    interface AppArticlesSearch {
    }
    interface AppArticlesSort {
    }
    interface AppCreateItem {
    }
    interface AppFormId {
        "item"?: any;
    }
    interface AppHeaderItem {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-admin": AppAdmin;
        "app-admin-filter": AppAdminFilter;
        "app-admin-header": AppAdminHeader;
        "app-admin-id": AppAdminId;
        "app-admin-id-article": AppAdminIdArticle;
        "app-admin-item": AppAdminItem;
        "app-admin-items": AppAdminItems;
        "app-admin-menu": AppAdminMenu;
        "app-admin-search": AppAdminSearch;
        "app-admin-sort": AppAdminSort;
        "app-article-id": AppArticleId;
        "app-articles": AppArticles;
        "app-articles-filter": AppArticlesFilter;
        "app-articles-header": AppArticlesHeader;
        "app-articles-item": AppArticlesItem;
        "app-articles-items": AppArticlesItems;
        "app-articles-menu": AppArticlesMenu;
        "app-articles-price": AppArticlesPrice;
        "app-articles-search": AppArticlesSearch;
        "app-articles-sort": AppArticlesSort;
        "app-create-item": AppCreateItem;
        "app-form-id": AppFormId;
        "app-header-item": AppHeaderItem;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-admin": LocalJSX.AppAdmin & JSXBase.HTMLAttributes<HTMLAppAdminElement>;
            "app-admin-filter": LocalJSX.AppAdminFilter & JSXBase.HTMLAttributes<HTMLAppAdminFilterElement>;
            "app-admin-header": LocalJSX.AppAdminHeader & JSXBase.HTMLAttributes<HTMLAppAdminHeaderElement>;
            "app-admin-id": LocalJSX.AppAdminId & JSXBase.HTMLAttributes<HTMLAppAdminIdElement>;
            "app-admin-id-article": LocalJSX.AppAdminIdArticle & JSXBase.HTMLAttributes<HTMLAppAdminIdArticleElement>;
            "app-admin-item": LocalJSX.AppAdminItem & JSXBase.HTMLAttributes<HTMLAppAdminItemElement>;
            "app-admin-items": LocalJSX.AppAdminItems & JSXBase.HTMLAttributes<HTMLAppAdminItemsElement>;
            "app-admin-menu": LocalJSX.AppAdminMenu & JSXBase.HTMLAttributes<HTMLAppAdminMenuElement>;
            "app-admin-search": LocalJSX.AppAdminSearch & JSXBase.HTMLAttributes<HTMLAppAdminSearchElement>;
            "app-admin-sort": LocalJSX.AppAdminSort & JSXBase.HTMLAttributes<HTMLAppAdminSortElement>;
            "app-article-id": LocalJSX.AppArticleId & JSXBase.HTMLAttributes<HTMLAppArticleIdElement>;
            "app-articles": LocalJSX.AppArticles & JSXBase.HTMLAttributes<HTMLAppArticlesElement>;
            "app-articles-filter": LocalJSX.AppArticlesFilter & JSXBase.HTMLAttributes<HTMLAppArticlesFilterElement>;
            "app-articles-header": LocalJSX.AppArticlesHeader & JSXBase.HTMLAttributes<HTMLAppArticlesHeaderElement>;
            "app-articles-item": LocalJSX.AppArticlesItem & JSXBase.HTMLAttributes<HTMLAppArticlesItemElement>;
            "app-articles-items": LocalJSX.AppArticlesItems & JSXBase.HTMLAttributes<HTMLAppArticlesItemsElement>;
            "app-articles-menu": LocalJSX.AppArticlesMenu & JSXBase.HTMLAttributes<HTMLAppArticlesMenuElement>;
            "app-articles-price": LocalJSX.AppArticlesPrice & JSXBase.HTMLAttributes<HTMLAppArticlesPriceElement>;
            "app-articles-search": LocalJSX.AppArticlesSearch & JSXBase.HTMLAttributes<HTMLAppArticlesSearchElement>;
            "app-articles-sort": LocalJSX.AppArticlesSort & JSXBase.HTMLAttributes<HTMLAppArticlesSortElement>;
            "app-create-item": LocalJSX.AppCreateItem & JSXBase.HTMLAttributes<HTMLAppCreateItemElement>;
            "app-form-id": LocalJSX.AppFormId & JSXBase.HTMLAttributes<HTMLAppFormIdElement>;
            "app-header-item": LocalJSX.AppHeaderItem & JSXBase.HTMLAttributes<HTMLAppHeaderItemElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
